### ISSUE TITLE
Failed to load plugin "view-sync"

### ISSUE THREAD

**Issue by rauchert** [RyotaUshio/obsidian-view-sync#2]
Hey,

thank you a lot for your work, I really enjoy pdf++!!! 

Now I wanted to check out view sync, but unfortunately I had some issues. First, I could not install it via Brat, I solved that by cloning the repository into my obsidian plugins folder. Now, I can see the plugin in the external plugins list in the obsidian settings, but when I want to activate it I get the error message: Failed to load plugin "view-sync". This occurs on my MacBook Air M2 as well as on my iPad Pro (a few years old).

Do you have any idea what could be the problem and how to solve it? :)

**Comment by rauchert** [comment]
I just noticed, that I do not have installed the obsidian livesync plugin. Maybe this missing requirement is the cause of the non-working installation via BRAT?

**Comment by RyotaUshio** [comment]
Hi, glad to hear you liked PDF++!

### BRAT installation

I quickly tested it, and I was able to install View Sync via BRAT without any issue on my MacBook Pro (2020 M1).
Do you see any error messages (either as a notification or in the developer console (Cmd+Opt+I))?

### Manual installation

If BRAT installation does not work, you can still install this plugin manually:

1. Go to [the release page of the latest version](https://github.com/RyotaUshio/obsidian-view-sync/releases/tag/0.2.1)
2. From "Assets", download `main.js`, `styles.css`, and `manifest.json`. Put these files under `.obsidian/plugins/view-sync`.
3. Now you will see "View Sync" in the community plugins list. If not, click the "Reload plugins" button.

(FIY, cloning the repository is another way of installation, but you need to generate the compiled `main.js` file by running `npm run build` after cloning. This requires [Node.js](https://nodejs.org/en/download/package-manager).)

**Comment by rauchert** [comment]
Thanks for your super fast reply! Strangely, I could not find any notification from BRAT, but I was successful with the manual installation and view sync is working now. Really nice. :)
